### ISSUE TITLE
What is your `break` vs `cond` reasoning?

### ISSUE THREAD

**Issue by pepe** [sogaiu/spork-http-sample#1]
Hello, I have seen that you are using `when` and `break` in your program: https://github.com/sogaiu/spork-http-sample/blob/master/main.janet#L7. Do you have any particular reason for not using `cond` for all three conditions? I am just curious. I am not saying it is wrong or anything like that :-).

**Comment by sogaiu** [comment]
I'm not sure there was any serious thought as this was thrown together [as a sample](https://github.com/janet-lang/janet/discussions/1348#discussioncomment-8008774).

Looking at it now, I think the two `when` forms indicate "failure"-ish cases so having early returns to mark them off as different from the "happy path", might be one way to view things (^^;

**Comment by pepe** [comment]
Yep. That makes sense. Thank you.
